"""Fixed-schema A2UI (v0.9) surface for hotel results.

The component tree is fixed (authored here, not generated by an LLM). The LLM only supplies the
hotel *data*. This returns the `a2ui_operations` container that both frontends look for:
    createSurface -> updateComponents -> updateDataModel

Only components from the A2UI *basic catalog* are used (Card, Column, Text, Button), so the same
payload renders in both the CopilotKit app and the direct @a2ui/react app.
"""
import uuid
from typing import Any

# Frontends map this id to their catalog. The CopilotKit app registers this exact id;
# the direct @a2ui/react app rewrites it to the basic catalog id before rendering.
CATALOG_ID = "copilotkit://trip-planner-catalog"
MAX_HOTELS = 4


def _text(value: Any, default: str = "") -> str:
    return default if value is None else str(value)


def build_hotel_operations(hotels: list[dict[str, Any]]) -> dict[str, Any]:
    hotels = hotels[:MAX_HOTELS]

    # A fresh surface id per call, so results from different questions can coexist
    surface_id = f"hotels-{uuid.uuid4().hex[:8]}"

    components: list[dict[str, Any]] = []
    data: dict[str, str] = {}
    card_ids: list[str] = []

    for i, h in enumerate(hotels):
        p = f"hotel{i}"
        card_ids.append(f"{p}-card")

        nights = h.get("nights")
        stay = f" · €{_text(h.get('total_eur'))} for {nights} night{'s' if nights != 1 else ''}" if nights else ""

        # Data model: flat keys keep the JSON Pointer paths ("/hotel0_name") trivial
        data[f"{p}_name"] = _text(h.get("name"), "Unknown hotel")
        data[f"{p}_meta"] = (
            f"{'★' * int(h.get('stars') or 0)} · {_text(h.get('area'))} · rating {_text(h.get('rating'))}"
        )
        data[f"{p}_price"] = f"€{_text(h.get('price_per_night_eur'))} / night{stay}"

        components += [
            {"id": f"{p}-card", "component": "Card", "child": f"{p}-col"},
            {
                "id": f"{p}-col",
                "component": "Column",
                "children": [f"{p}-name", f"{p}-meta", f"{p}-price", f"{p}-book"],
            },
            {"id": f"{p}-name", "component": "Text", "variant": "h4", "text": {"path": f"/{p}_name"}},
            {"id": f"{p}-meta", "component": "Text", "variant": "caption", "text": {"path": f"/{p}_meta"}},
            {"id": f"{p}-price", "component": "Text", "variant": "body", "text": {"path": f"/{p}_price"}},
            {
                "id": f"{p}-book",
                "component": "Button",
                "child": f"{p}-book-label",
                "action": {"event": {"name": "book_hotel", "context": {"hotelId": _text(h.get("id"))}}},
            },
            {"id": f"{p}-book-label", "component": "Text", "text": "Book"},
        ]

    # The root component must have the id "root"
    components.insert(
        0,
        {"id": "root", "component": "Column", "children": ["heading", *card_ids]},
    )
    components.insert(1, {"id": "heading", "component": "Text", "variant": "h3", "text": "Hotel options"})

    return {
        "a2ui_operations": [
            {"version": "v0.9", "createSurface": {"surfaceId": surface_id, "catalogId": CATALOG_ID}},
            {"version": "v0.9", "updateComponents": {"surfaceId": surface_id, "components": components}},
            {"version": "v0.9", "updateDataModel": {"surfaceId": surface_id, "path": "/", "value": data}},
        ]
    }
